# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch: {}
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: docker

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup bepinex nuget source
      run: dotnet nuget add source https://nuget.bepinex.dev/v3/index.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Create assembly directory
      run: mkdir assembly
    - name: Copy dll to assembly
      run: cp bin/Debug/net472/AIM9XMod.dll assembly/AIM9XMod.dll
    - name: Copy sounds to assembly
      run: cp -R SeekerNoises assembly/
    
    - name: Create release directory
      run: mkdir release

    - name: Move into assembly dir
      run: cd assembly

    - name: Zip files into release
      run: zip -r ../release/aim9x.zip .

    - name: Release
      uses: actions/forgejo-release@v2.12.0
      with:
        direction: upload
        url: https://git.pr0.tech/
        repo: rs/screamingMissiles
        token: ${{ secrets.WRITE_TOKEN }}
        tag: v1.0.0
        release-dir: release
        release-notes: "HELLO WORLD"

